# Generated by Django 5.2.8 on 2025-11-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_specialoffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_name', models.CharField(max_length=255, verbose_name='Название продвижения')),
                ('discount_type', models.CharField(choices=[('percent', 'Процентная скидка'), ('fixed', 'Фиксированная сумма')], max_length=20, verbose_name='Тип скидки')),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Процент или фиксированная сумма', max_digits=10, verbose_name='Размер скидки')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('minimum_order_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Минимальная сумма заказа')),
                ('priority', models.IntegerField(default=0, help_text='Большее число означает более высокий приоритет', verbose_name='Приоритет')),
                ('applicable_products', models.ManyToManyField(blank=True, related_name='promotions', to='main.product', verbose_name='Применимые продукты')),
            ],
            options={
                'verbose_name': 'Продвижение',
                'verbose_name_plural': 'Продвижения',
                'ordering': ['-priority', 'start_date'],
            },
        ),
    ]
