# Generated by Django 5.2.8 on 2025-11-26 05:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_promotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_status', models.CharField(choices=[('basic', 'Basic'), ('silver', 'Silver'), ('gold', 'Gold')], default='basic', max_length=20, verbose_name='Статус участника')),
                ('loyalty_points', models.PositiveIntegerField(default=0, verbose_name='Баллы лояльности')),
                ('total_spending', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая сумма покупок')),
                ('registration_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty', to='main.client', verbose_name='Клиент')),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyRecalculationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recalculated_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата перерасчёта')),
                ('old_points', models.IntegerField(verbose_name='Старые баллы')),
                ('new_points', models.IntegerField(verbose_name='Новые баллы')),
                ('details', models.TextField(verbose_name='Подробности начисления')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client', verbose_name='Клиент')),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_type', models.CharField(choices=[('discount_5', 'Скидка 5€'), ('discount_10_percent', 'Скидка 10%'), ('upgrade_level', 'Повышение уровня')], max_length=30, verbose_name='Тип награды')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата погашения')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client', verbose_name='Клиент')),
                ('created_promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.promotion', verbose_name='Созданное продвижение')),
            ],
        ),
    ]
